### ISSUE TITLE
CSS opmerkingen

### ISSUE THREAD

**Issue by KaanKalmi** [Vikkeyeftimov/connect-your-tribe-profile-card#4]
```css
.first-slide{
  p{
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    font-size: var(--fontpsize);
  }
}
```
Is de P hier niet een nested property? je hoort het namelijk als `& p{...}` te noteren!
